//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drugstore.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class kurs_05_02_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kurs_05_02_order()
        {
            this.kurs_05_02_basket = new HashSet<kurs_05_02_basket>();
        }
    
        public int id_order { get; set; }
        public Nullable<int> total_sum { get; set; }
        public Nullable<int> bonuses_for_order { get; set; }
        public string address { get; set; }
        public Nullable<int> id_payment_method { get; set; }
        public string order_code { get; set; }
        public Nullable<bool> finished { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kurs_05_02_basket> kurs_05_02_basket { get; set; }
        public virtual kurs_05_02_payment_method kurs_05_02_payment_method { get; set; }
    }
}
