//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drugstore.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class kurs_05_02_cure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kurs_05_02_cure()
        {
            this.kurs_05_02_basket = new HashSet<kurs_05_02_basket>();
        }
    
        public int id_cure { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> id_category { get; set; }
        public Nullable<int> id_release_form { get; set; }
        public Nullable<System.DateTime> shelf_life { get; set; }
        public string volume { get; set; }
        public Nullable<int> id_manufacturer { get; set; }
        public string in_stock { get; set; }
        public Nullable<bool> prescription { get; set; }
        public byte[] image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kurs_05_02_basket> kurs_05_02_basket { get; set; }
        public virtual kurs_05_02_cure_category kurs_05_02_cure_category { get; set; }
        public virtual kurs_05_02_manufacturer kurs_05_02_manufacturer { get; set; }
        public virtual kurs_05_02_release_form kurs_05_02_release_form { get; set; }
    }
}
