//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drugstore.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class kurs_05_02_basket
    {
        public int id_basket { get; set; }
        public Nullable<int> id_cure { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> cure_quantity { get; set; }
        public Nullable<int> id_order { get; set; }
    
        public virtual kurs_05_02_cure kurs_05_02_cure { get; set; }
        public virtual kurs_05_02_order kurs_05_02_order { get; set; }
        public virtual kurs_05_02_user kurs_05_02_user { get; set; }
    }
}
